[package]
name = "cobject"
version = "0.0.2"
edition = "2024"

[lib]
#proc-macro = true

[dependencies]
minifb = "0.28.0"
image = "0.25.9"
#syn = { version = "2", features = ["full"] }
#quote = "1"
#proc-macro2 = "1"